export type TradeScopeStatus = 'complete' | 'partial' | 'missing'

export type TradeScopeReviewEntry = {
  category: string
  trade: string
  status: TradeScopeStatus
  status_icon: '✅' | '⚠️' | '❌'
  notes: string
  page_refs: string[]
}

export type TradeScopeReviewSummary = {
  complete: number
  partial: number
  missing: number
  notes: string
}

export type TradeScopeReview = {
  items: TradeScopeReviewEntry[]
  summary: TradeScopeReviewSummary
  raw: Array<TradeScopeReviewEntry | { summary: TradeScopeReviewSummary }>
}

type NormalizeOptions = {
  defaultNotes?: string
}

const DEFAULT_NOTES = 'Trade scope review generated by AI analysis.'

function resolveStatus(statusOrIcon?: string): { status: TradeScopeStatus; icon: '✅' | '⚠️' | '❌' } {
  if (!statusOrIcon) {
    return { status: 'partial', icon: '⚠️' }
  }

  const normalized = statusOrIcon.toString().toLowerCase().trim()

  if (normalized === 'complete' || statusOrIcon === '✅') {
    return { status: 'complete', icon: '✅' }
  }

  if (normalized === 'missing' || statusOrIcon === '❌') {
    return { status: 'missing', icon: '❌' }
  }

  return { status: 'partial', icon: '⚠️' }
}

export function normalizeTradeScopeReview(
  existing: any,
  issues: any[],
  options: NormalizeOptions = {}
): TradeScopeReview {
  const defaultNotes = options.defaultNotes || DEFAULT_NOTES

  let rawEntries: any[] = []
  let summaryFromExisting: TradeScopeReviewSummary | null = null

  if (Array.isArray(existing)) {
    rawEntries = existing
  } else if (existing?.raw && Array.isArray(existing.raw)) {
    rawEntries = existing.raw
  } else if (existing?.items && Array.isArray(existing.items)) {
    rawEntries = existing.items
    if (existing.summary) summaryFromExisting = existing.summary
  }

  const items: TradeScopeReviewEntry[] = []

  rawEntries.forEach(entry => {
    if (!entry || typeof entry !== 'object') return

    if (entry.summary) {
      summaryFromExisting = entry.summary
      return
    }

    const { status, icon } = resolveStatus(entry.status_icon || entry.status)

    items.push({
      category: entry.category || entry.group || 'General',
      trade: entry.trade || entry.scope || entry.category || 'General',
      status,
      status_icon: icon,
      notes: entry.notes || entry.detail || entry.description || '',
      page_refs: Array.isArray(entry.page_refs) ? entry.page_refs : []
    })
  })

  if (items.length === 0 && Array.isArray(issues) && issues.length > 0) {
    issues.forEach(issue => {
      if (!issue || typeof issue !== 'object') return
      const severity = (issue.severity || issue.level || '').toString().toLowerCase()
      const statusSeed = issue.status_icon || issue.status || (severity === 'critical' ? '❌' : severity === 'info' ? '✅' : '⚠️')
      const { status, icon } = resolveStatus(statusSeed)
      items.push({
        category: issue.category || issue.group || 'General',
        trade: issue.trade || issue.category || 'General',
        status,
        status_icon: icon,
        notes: issue.description || issue.detail || issue.message || issue.notes || '',
        page_refs: Array.isArray(issue.page_refs)
          ? issue.page_refs
          : issue.pageNumber
            ? [`P-${issue.pageNumber}`]
            : []
      })
    })
  }

  const summary = summaryFromExisting || items.reduce<TradeScopeReviewSummary>((acc, entry) => {
    if (entry.status === 'complete') acc.complete += 1
    else if (entry.status === 'missing') acc.missing += 1
    else acc.partial += 1
    return acc
  }, {
    complete: 0,
    partial: 0,
    missing: 0,
    notes: defaultNotes
  })

  if (!summary.notes) summary.notes = defaultNotes

  const raw: TradeScopeReview['raw'] = [
    ...items,
    { summary }
  ]

  return {
    items,
    summary,
    raw
  }
}
